package-lock.json, package.json, src/app/page.tsx, src/components/ui/dropdown-menu.tsx, tailwind.config.ts
=> feat : 디자인시스템 타이포그래피 추가

src/app/(main)/(home)/layout.tsx, src/app/(main)/(home)/recommendations/page.tsx, src/app/(main)/layout.tsx, src/components/feature/home/homeHeader.tsx, src/components/feature/home/homeTab.tsx, src/components/feature/home/homeTabs.tsx, src/components/feature/recommendations/eventBanner.tsx
=> 10 feat 추천탭 이벤트 베너

build.sh, src/api/resource/login.ts, src/api/resource/search.ts
=> Chore : 빌드 스크립트 추가

src/api/resource/login.ts, src/app/api/oauth/callback/kakao/route.ts, src/components/feature/login/kakaoLoginButton.tsx
=> Chore: 환경변수명 변경

src/api/resource/login.ts, src/api/service/login.ts, src/app/(login)/login/social-register/page.tsx, src/components/common/header.tsx, src/components/feature/login/kakaoLoginButton.tsx, src/components/feature/social-register/socialRegisterForm.tsx, src/components/feature/social-register/socialRegisterHeader.tsx, src/types/login.ts
- [ X]  기능 **추가 - Add**
- Projects 이슈 링크
-
=> 66 feat 소셜 로그인

next.config.js, src/api/resource/cart.ts, src/api/resource/order.ts, src/api/resource/signup.ts, src/api/util/instance.ts, src/app/(cart)/order/page.tsx, src/app/api/members/check-loginId/route.ts, src/app/api/oauth/callback/kakao/route.ts, src/components/feature/social-register/socialRegisterForm.tsx, src/middleware.ts, src/types/order.ts, src/types/product.ts
=> 77 미들웨어 header cookie 설정 작업

package-lock.json, src/api/resource/login.ts, src/api/resource/order.ts, src/api/util/instance.ts, src/app/api/members/authenticate/route.ts, src/app/api/members/check-loginid/route.ts, src/app/api/members/signup/route.ts, src/app/api/orders/payment/route.ts, src/components/feature/login/loginForm.tsx, src/components/feature/signup/signupForm.tsx, src/middleware.ts, src/types/order.ts
- [x ]  기능 **추가 - Add**
- Projects 이슈 링크
-
=> Feat : 일반 로그인 쿠키 설정 및 미들웨어 헤더 설정

src/app/items/[itemId]/layout.tsx
=> Fix: 배포 시 에러 fix

src/api/resource/items.ts, src/app/(main)/(home)/best-items/page.tsx, src/app/(main)/(home)/new-arrivals/page.tsx, src/app/add-review/layout.tsx, src/app/add-review/page.tsx, src/app/api/mypage/member/route.ts, src/components/feature/addReview/AddReviewHeader.tsx
=> 18 feat 후기작성

src/app/(main)/(category)/category/page.tsx
=> Fix: 베포 시 fetch failed 에러 fix

next.config.js, src/api/util/instance.ts, src/app/(main)/(category)/category/page.tsx, src/app/add-review/page.tsx, src/app/api/addReview/route.ts, src/app/edit-info/layout.tsx, src/app/edit-info/page.tsx, src/app/items/[itemId]/layout.tsx, src/components/feature/editInfo/EditInfoHeader.tsx, src/components/feature/item/BottomTab.tsx, src/components/feature/myPage/wish/WishedItem.tsx
=> Refactor: baseURL변경

src/api/resource/editInfo.ts, src/api/resource/member.ts, src/api/service/editinfo.ts, src/app/(main)/(myPage)/myPage/page.tsx, src/app/add-review/page.tsx, src/app/api/addReview/route.ts, src/app/api/members/editinfo/route.ts, src/app/api/members/memberInfo/route.ts, src/app/edit-info/page.tsx, src/components/feature/editInfo/EditInfoForm.tsx, src/components/feature/myPage/LoggedInProfile.tsx, src/components/feature/myPage/MyMenus.tsx, src/components/feature/myPage/NotLoggedInPeofile.tsx, src/lib/schema/editInfo.ts, src/types/editinfo.ts
=> 개인정보 수정 및 마이페이지 프로필 

src/api/resource/editInfo.ts, src/api/resource/member.ts, src/api/service/editinfo.ts, src/app/(main)/(myPage)/myPage/page.tsx, src/app/add-review/page.tsx, src/app/api/members/editinfo/route.ts, src/app/api/members/memberInfo/route.ts, src/app/edit-info/page.tsx, src/components/feature/editInfo/EditInfoForm.tsx, src/components/feature/myPage/LoggedInProfile.tsx, src/components/feature/myPage/NotLoggedInPeofile.tsx, src/types/editinfo.ts
=> Fix: lint error 수정

src/api/resource/editInfo.ts, src/app/api/members/editinfo/route.ts, src/components/feature/editInfo/EditInfoForm.tsx
=> Refactor: 개인정보 수정 비밀번호 잘못입력 시 모달창 뜨도록 수정

src/components/feature/item/BottomTab.tsx, src/components/feature/orderComplete/orderCompleteNavButton.tsx, src/components/feature/orderDetail/orderDetailButtonGroup.tsx, src/components/feature/orderDetail/orderDetailList.tsx, src/store/client/orderSlice.ts
=> Feat : 리뷰쓰기 쿼리 파라미터 추가

src/app/(main)/(myPage)/registration/layout.tsx, src/app/(main)/(myPage)/registration/page.tsx, src/components/feature/myPage/MyMenus.tsx, src/middleware.ts
=> Feat: 로그인/비로그인 mypage 페이지 분리

src/components/feature/myPage/MyMenuButton.tsx, src/components/feature/myPage/MyMenuContainer.tsx, src/components/feature/myPage/MyMenuItem.tsx, src/components/feature/myPage/MyMenus.tsx
=> Refactor : 링크 아이템 버튼 아이템 수정

src/app/(main)/(home)/recommendations/page.tsx, src/app/(main)/(search)/search/[item]/layout.tsx, src/app/add-review/page.tsx, src/app/api/addReview/route.ts, src/components/common/filters/FilterBottomSheet.tsx, src/components/common/filters/FilterBottomSheetOptions.tsx, src/components/feature/orderDetail/orderDetailButtonGroup.tsx
=> Refactor: 주문 상세 -> 리뷰 페이지 접근할 수 있도록 수정

src/app/items/[itemId]/page.tsx, src/components/feature/item/ItemDetailInfo.tsx, src/components/feature/item/ItemMainInfo.tsx, src/components/feature/item/ItemReview.tsx
클라이언트 컴포넌트의 자식 컴포넌트로 서버 컴포넌트를 넣어놓은 코드 수정
- Projects 이슈 링크
-
=> Fix: itemDtail 클라이언트 컴포넌트에서 aync/await 사용시 무한 패치 버그 수정

src/app/(cart)/cart/page.tsx, src/app/(cart)/order-detail/[orderId]/page.tsx, src/app/(cart)/order-history/page.tsx, src/app/(cart)/order/page.tsx
=> fix " add dynamic-force

src/app/items/[itemId]/layout.tsx, src/app/items/[itemId]/page.tsx
=> fix add dynamic force to item detail

src/app/api/cart/insert/route.ts
=> fix test header

src/app/api/cart/delete/route.ts, src/app/api/cart/item/add/route.ts, src/app/api/cart/item/minus/route.ts
=> fix invalid transfer-encoding header 장바구니 아이템 API

src/components/feature/orderDetail/orderDetailItem.tsx
=> fix 주문상세 페이지 링크 오탈자 수정

src/api/resource/category.ts, src/api/resource/home.ts, src/api/resource/search.ts, src/app/(main)/categories/[categoryName]/layout.tsx, src/app/(main)/categories/[categoryName]/page.tsx, src/components/feature/category/categoryItem/CategoryFilter.tsx, src/components/feature/category/categoryItem/CategoryItemsList.tsx
필터 파라미터 이름 수정 (백엔드 api 링크에 넣는 파리미터 이름)
상품 리스트 개수 표시를 위헤 searchParams 사용하여 파라미터로 상품api 콜하는 코드 추가
=> 필터, 카테고리 리팩토링

src/api/resource/category.ts, src/api/resource/home.ts
=> Fix: 신상품 필터 api호출 시 백엔드 url로 바로 요청

src/api/resource/category.ts, src/app/(main)/categories/[categoryName]/page.tsx, src/app/api/logout/route.ts, src/components/common/filters/FilterButtons.tsx, src/components/feature/category/categoryItem/CategoryFilter.tsx
=> 112 배포 에러 fix

src/api/resource/category.ts, src/components/feature/category/categoryItem/CategoryFilter.tsx
=> Refactor: 불필요한 로그 제거

src/app/api/members/authenticate/route.ts, src/app/api/members/check-email/route.ts, src/app/api/members/check-loginid/route.ts, src/app/api/members/editinfo/route.ts, src/app/api/members/memberInfo/route.ts, src/app/api/members/signup/route.ts, src/app/api/members/socialRegister/route.ts, src/app/api/members/verify-password/route.ts, src/app/api/mypage/member/route.ts, src/components/feature/connect/connectInfo.tsx, src/lib/middlewares/setAuthToken.ts, src/lib/middlewares/setProviderInfo.ts, src/lib/utils.ts
=> Feat : connect 페이지 유저 로그인 ID 표기 반영

src/components/feature/orderDetail/orderDetailList.tsx, src/lib/utils.ts
=> Fix : 주문 상세 Date 처리

.gitignore, next.config.js, package-lock.json, package.json, src/app/api/orders/route.ts, src/components/ui/radio-group.tsx
=> Redeployment error fix

src/app/(main)/categories/category/page.tsx
=> Fix : categories/category runtime 변경

src/api/resource/payment.ts, src/api/service/payment.ts, src/app/(cart)/order/page.tsx, src/app/api/orders/payment-verify/route.ts, src/app/layout.tsx, src/components/feature/order/orderForm.tsx, src/types/payment.ts
portone 테스트 결제 PG: tosspay, 간편결제: kakakopay
- Projects 이슈 링크
-
=> Feat: 결제 연동 -완-

package-lock.json, package.json, src/components/feature/order/OrderPaymentMethod.tsx, src/components/feature/order/orderAddress.tsx, src/components/feature/order/orderForm.tsx, src/lib/post/daumPost.ts, src/lib/schema/order.ts
=> Feat : 다음 주소 api 적용

src/app/(main)/categories/category/page.tsx
=> test : edge runtime fetch

src/components/feature/order/orderForm.tsx
=> Fix : 결제 api 에러 메세지 적용

src/components/common/modal/checkModal.tsx, src/components/feature/myPage/MyMenus.tsx, src/components/feature/order/orderCoupon.tsx, src/components/feature/order/orderForm.tsx, src/lib/payment/portOnePayment.ts
=> Feat : 결제 쿠폰 기능 추가

public/dummyData/faqData.json, src/app/(main)/(myPage)/myPage/page.tsx, src/app/add-inquiry/page.tsx, src/app/items/[itemId]/layout.tsx, src/components/feature/addInquiry/AddInquiryBottomSeat.tsx, src/components/feature/faq/FAQBottomSeat.tsx, src/components/feature/faq/FAQItemList.tsx, src/components/feature/item/ItemMainInfo.tsx, src/components/feature/myPage/LoggedInProfile.tsx, src/components/feature/order/orderCoupon.tsx, src/components/ui/toast.tsx, tailwind.config.ts
=> 140 feat 마이페이지 멤버등급추가

src/components/feature/order/orderForm.tsx, src/components/ui/checkbox.tsx, src/components/ui/input.tsx, src/components/ui/radio-group.tsx, src/lib/payment/portOnePayment.ts, src/lib/utils.ts, src/types/payment.ts
=> Refactor : 결제 프로세스 리팩토링

src/app/(cart)/layout.tsx, src/app/layout.tsx
=> fix: 스크립트 로딩 개선
